### ISSUE TITLE
Some guilds are not cached

### ISSUE THREAD

**Issue by gouenji-shuuya** [Pycord-Development/pycord#1050]
### Summary

`len(bot.guilds)` returns a lesser count than the one shown in the invite page. And yes, invite page count changes in real time.

### Reproduction Steps

Used `len(bot.guilds)` to get server count, and compared it with server count showed by Discord on the invite page.

### Minimal Reproducible Code

```python
await ctx.send(len(self.bot.guilds))  # For a command in a Cog.
```

### Expected Results

Guild count returned should be same as that on the invite page (For instance: 382 right now)

### Actual Results

Guild count returned is not the same (For instance: 378 right now)

### Intents

bans, dm_messages, emojis, emojis_and_stickers, guild_messages, guild_reactions, guilds, members, messages, reactions, scheduled_events

### System Information

- Python v3.10.2-final
- py-cord v2.0.0-beta
    - py-cord pkg_resources: v2.0.0b4
- aiohttp v3.8.1

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

When I add the bot in a server, the internal guild count also increases (as well as the invite page count).

It seems some guilds are not being cached which is resulting in this mismatch.

---

Also, when I run the following code:

```python
guilds = await self.bot.fetch_guilds(limit=None).flatten()
await ctx.send(len(guilds))
```

The bot sends `100`.

But when I run the following:

```python
guilds = await self.bot.fetch_guilds(limit=400).flatten()
await ctx.send(len(guilds))
```

The bot sends `199`.

Both are not equal to the real guild count. On top of that, `limit=None` should not even default to 100.

**Comment by Middledot** [comment]
The guild count shown on the invite page has inaccuracies like offsets and roundings and isn't a good way to verify the guild count. The reason `bot.fetch_guilds` doesn't give the full amount of guilds is because it can [only return 200 at a time](https://canary.discord.com/developers/docs/resources/user#get-current-user-guilds) with the default in pycord set to 100. You need to paginate with the [`before` and `after` parameters](https://docs.pycord.dev/en/master/api.html#discord.Client.fetch_guilds) to get the rest of the guilds.

**Comment by gouenji-shuuya** [comment]
How do you paginate with before and after? The docs should be clearer about this. And default is 100, but `None` as argument to limit also is defaulting to 100 when the docs say otherwise.

```python
from datetime import datetime
from Factory.embed import create_embed

guilds = await self.bot.fetch_guilds(
    limit=500,
    before=datetime.now(),
    after=datetime.fromtimestamp(0)
).flatten()

await ctx.send(len(guilds))
```

This sends 500, which is impossible.

```python
from datetime import datetime
from Factory.embed import create_embed

guilds = set(await self.bot.fetch_guilds(
    limit=500,
    before=datetime.now(),
    after=datetime.fromtimestamp(0)
).flatten())

await ctx.send(len(guilds))
```

This sends 104.

---

In the above example where it sent 199, enclosing it inside a set gives 100. Which means I am getting duplicated entries.

**Comment by Middledot** [comment]
Pagination is supposed to be done with objects in most use cases because when you paginate with timestamps, it gets transformed into IDs/snowflakes anyways.

For paginating, doing `before=discord.Object(id=1234567890)` for example checks for objects of which the ID is smaller than that.
```python
messages = []
# get 2 most recent messages in chat
payload = await channel.history(limit=2).flatten()
messages += payload
# oldest of the 2 messages
last_msg = payload[-1]
# get 2 last messages sent before the oldest message of the previous payload
payload = await channel.history(limit=2, before=last_msg).flatten()
messages += payload
```
so in
```
msg 1
msg 2
msg 3
newest message
```
"newest message" and "msg 3" are fetched first, and then a second request is made for 2 messages before "msg 3".



It is true that it's not documented correctly saying that `None` fetches all guilds.
https://github.com/Pycord-Development/pycord/blob/b82092c6026567904eb77e341333694223c2debb/discord/iterators.py#L577-L578

**Comment by gouenji-shuuya** [comment]
> Could you elaborate on how you got 500 guilds? I'm running the exact same code and it errors out.

I run the mentioned code from my bot. The code and output is already mentioned.

I'm sorry, but this is not working the way it is supposed to be, and you are just actively trying to avoid any issues with it.
