### ISSUE TITLE
Hot changes

### ISSUE THREAD

**Issue by BetThical** [Pycord-Development/pycord#110]
### Summary

A feature wich allows you to make changes on the go

### What is the feature request for?

The core library

### The Problem

It's simply to dont have to restart the bot every moment i want to change something.

### The Ideal Solution

 It would be nice that there were a way to "auto-update" it

**Comment by Dorukyum** [comment]
You can always update the bot's attributes.

**Comment by MhmCats** [comment]
You can use extensions for this, you can have a cog in your extension and load it at the start. Then, if you make a change to it [the extension] you can reload it. If you are talking about making changes to stuff on the bot e.g. `bot.process_commands` then I don't see anything wrong with restarting it, this can be make even easier by using a process manager (such as systemd on Linux systems) so that it automatically restarts the bot if you stop it.

**Comment by BobDotCom** [comment]
This is possible using cogs, but not otherwise. Cogs can be unloaded, changed, then loaded again and the changes will be added without restarting. It is impractical and impossible within reason to implement this for the main file.

**Comment by laundmo** [comment]
@BetThical if you really want something like this maybe look into libraries such as [julvo/relaoding](https://pypi.org/project/reloading/)
