### ISSUE TITLE
await ctx.defer() do 404 Not Found (error code: 10062): Unknown interaction

### ISSUE THREAD

**Issue by Creveoolus** [Pycord-Development/pycord#1487]
### Summary

await ctx.defer() do 404 Not Found (error code: 10062): Unknown interaction

### Reproduction Steps

- Create an command
- Use `await ctx.defer()`
- Run another command
- Use command with `await ctx.defer()`

### Minimal Reproducible Code

```python
Used in cog

	user = SlashCommandGroup(
		'user',
		description='User commands'
	)


	@user.command()
	async def stats(self, ctx: discord.ApplicationContext, member: Option(discord.User, 'Specify an user')):
		member = ctx.author if member is None else member

		await ctx.defer()

```
```


### Expected Results

Interaction will be defered

### Actual Results

Throws an `discord.errors.ApplicationCommandInvokeError: Application Command raised an exception: NotFound: 404 Not Found (error code: 10062): Unknown interaction` error

### Intents

all

### System Information

C:\Users\User>python -m discord -v 
- Python v3.10.4-final
- py-cord v2.0.0-final
- aiohttp v3.7.4.post0
- system info: Windows 10 10.0.22000

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

I have deadline till tomorow, pls help

**Comment by plun1331** [comment]
You are most likely deferring after the 3 second period where you must respond

**Comment by Lulalaby** [comment]
Check the hosts speed. Maybe execute a speedtest. This is no lib issue.

**Comment by Creveoolus** [comment]
> Check the hosts speed. Maybe execute a speedtest. This is no lib issue.
Actually it's running on my computer. So it can not be the problem.


> You are most likely deferring after the 3 second period where you must respond
Thanks for the answer, i might test it

**Comment by Creveoolus** [comment]
Allright, i tested it, doesn't work. Defer stops working after the on_message event, might that help.

**Comment by RafaelSolVargas** [comment]
I got this same error in a situation that might help someone.
My Discord Bot [Vulkan](https://github.com/RafaelSolVargas/Vulkan) works with the multiprocessing python module to create other processes to play the music. When a process is created it duplicates the code in memory, in fact you increase the number of instances of your program.
If any slash command is send, the command is received by all yours program instances, and when the copies of the principal process try to defer the interaction object they will fail with this http 404 error, because they cannot access the interaction object (due to others processing).
