### ISSUE TITLE
Document `discord.channelType`

### ISSUE THREAD

**Issue by Icebluewolf** [Pycord-Development/pycord#1510]
### Summary

Document discord.channelType. Also make it so the argument accepts the actually channel type or string and not and int for the ID of the channel type

### What is the feature request for?

The documentation

### The Problem

So people stop asking is its possible and so it is more clear.

### The Ideal Solution

Document it.

### Additional Context

I would do this but I have no idea how the documentation files work

**Comment by Lulalaby** [comment]
Then do it wolfy ♥️

**Comment by jdelucca** [comment]
https://discord.com/channels/881207955029110855/881735314987708456/1029044538523799633

When using slash command options, if the slash command is asking for a channel type, make sure that the types show up as both ints and names, so that you don't have to go into documentation while trying to do a slash command. (if this behavior still exists)

**Comment by jdelucca** [comment]
Looking into it, when using the channel type as an option, first Option recognizes that the option of class Enum, then overrides the description with the inspect.getdoc() of the enum. 
Because there was no docstring for the enum classes, you would get "No description provided" even when you gave the Option a description string.
<img width="1077" alt="image" src="https://user-images.githubusercontent.com/76178990/195375596-8446554d-cf60-4102-91df-d2319823a205.png">

**Comment by Dorukyum** [comment]
Completed in #1699.
