### ISSUE TITLE
Introduce proper handling for cloudflare rate limits

### ISSUE THREAD

**Issue by diminDDL** [Pycord-Development/pycord#1543]
### Summary

Handle cloudflare rate limits smarter

### What is the feature request for?

The core library

### The Problem

Today I had a person run my bot on a server hosting several other bots. The result was it threw a `discord.errors.HTTPException: 429 Too Many Requests (error code: 0): You are being blocked from accessing our API temporarily due to exceeding our rate limits frequently. Please read our docs at https://discord.com/developers/docs/topics/rate-limits to prevent this moving forward.` and stopped. Due to what seems to be the server hitting the cloud flare limit with all of those bots (presumably some of them were under load and producing many requests at that time.) 

### The Ideal Solution

The other bots on that server are running `JDA (Java Discord API)` and they seemed to have a system for handling the rate limit and re trying after some time see: https://github.com/DV8FromTheWorld/JDA/pull/1355. I would like to propose a something for handling such cases and making the bot being able to recover from them by perhaps attempting to reconnect after a while. (I am being very naive here I have no idea how this works internally or how one would implement this.)

**Comment by VincentRPS** [comment]
This isn’t the cloudflare ratelimit, this is Discord's manual global ratelimit for spamming to much, iirc, it lasts for about an hour so it’s not really possible to handle that.

**Comment by plun1331** [comment]
- This does not appear to be a cloudflare ban.
- If you are repeatedly exceeding the ratelimit to the point where you are API banned, you should consider refactoring your code, or for large bots, contacting Discord and requesting a larger ratelimit.
- While it would be convenient to have something that reconnects once the ban expires, I don't think it's a great idea. If your bot got itself API banned, you should be looking into and fixing it yourself instead of ignoring it and letting the library reconnect for you.

**Comment by diminDDL** [comment]
Okay fair enough I guess.
