### ISSUE TITLE
Accessing Raw Interaction Data in `interaction_metadata`

### ISSUE THREAD

**Issue by DIPx69** [Pycord-Development/pycord#2498]
### Summary

In previous versions, raw interaction data could be accessed using message.interaction.data. However, since the 2.6 update, this method has changed

### What is the feature request for?

The core library

### The Problem

The issue is that since the 2.6 update, we can no longer access raw interaction data using `message.interaction.data` as we did previously

### The Ideal Solution

1. In `interactions.py`, within the `InteractionMetadata` class, add `data` to the `__slots__`.
2. Set `self.data = data` within the class.

![IMG_20240712_095811](https://cdn.discordapp.com/attachments/1261158497576292402/1261170718167666688/Screenshot_2024-07-12-09-56-07-100_com.termux.jpg?ex=6691fc42&is=6690aac2&hm=4fc1e19abeb292b5dd8458803906f880f095d9221f3ee3781e1b5a0d8919c21d&)
![IMG_20240712_095811](https://github.com/user-attachments/assets/ba16229c-5bf7-4b98-9494-cf94ae8d3a87)

This modification allows you to access the raw interaction data as `message.interaction.data`, similar to the previous implementation before the 2.6 update

**Comment by Lulalaby** [comment]
We can't something not existing:
![image](https://github.com/user-attachments/assets/d86c9c69-9248-4865-83f7-1b9a19242bdb)
![image](https://github.com/user-attachments/assets/b06bc661-7a89-4c11-839b-d44687454551)

The difference between the old `interaction` info:
![image](https://github.com/user-attachments/assets/873fcad5-3f00-4b5e-8c6f-116d9cc7d1cd)
And the new `interaction_metadata` info:
![image](https://github.com/user-attachments/assets/240bba6a-87ed-4cd6-bd8f-6ffca06ec29b)
is that:
- you have only the `user` instead of `member`
- the `name` of the command is missing

I'm a bit confused tho why we would have had that before, since interaction infos on messages never had the real interaction saved, that'd have been a privacy concern to be honest (api side). I can imagine that we monkey-patched the last interaction data on it, but from discord side we never receive interaction.data on a message object.

Maybe I'm still too tired, but it seems like something we can't do?

@plun1331 / @NeloBlivion could you double check for me

**Comment by NeloBlivion** [comment]
I believe what they mean is that in the version before Discord migrated to `interaction_metadata`, the old `MessageInteraction` class assigned [`self.data = data`](https://github.com/Pycord-Development/pycord/blob/master/discord/interactions.py#L1470) so you could access the raw data from Discord; the new `InteractionMetadata` class does not do this (as an aside, I honestly think every Discord Model should assign the raw data as an attribute so that users can freely make use of it if necessary.)

**Comment by Lulalaby** [comment]
Ah fair, well we can leave that open then, but definitely low prio since it's nothing spec related

**Comment by NeloBlivion** [comment]
Indeed, pretty easy fix and you can still access the old `message.interaction.data` (or you should be able to? it's right above message.interaction_metadata)

**Comment by plun1331** [comment]
> Indeed, pretty easy fix and you can still access the old `message.interaction.data` (or you should be able to? it's right above message.interaction_metadata)

`message.interaction` is deprecated and could get removed, thus we would rather not rely on it

**Comment by NeloBlivion** [comment]
Ah of course, but in the short term they can still make use of it

**Comment by DIPx69** [comment]
> Ah of course, but in the short term they can still make use of it

I am using version 2.6 with the changes in the code, and my codebase is working fine. I hope these issues will be patched in the next update. Thanks for helping me

**Comment by DIPx69** [comment]
> > Indeed, pretty easy fix and you can still access the old `message.interaction.data` (or you should be able to? it's right above message.interaction_metadata)
> 
> `message.interaction` is deprecated and could get removed, thus we would rather not rely on it

I can still use ` _interaction ` without any deprecated warnings

**Comment by NeloBlivion** [comment]
Don't think we included a warning in code because it'd trigger on every message without any user involvement, it's been marked as deprecated in the docs though.

**Comment by DIPx69** [comment]
> Don't think we included a warning in code because it'd trigger on every message without any user involvement, it's been marked as deprecated in the docs though (or maybe we could make it a property?)

As I know  `MessageInteraction`  class will be removed from the codebase in the next update.

**Comment by Lulalaby** [comment]
> I am using version 2.6 with the changes in the code, and my codebase is working fine. I hope these issue will be patched in the next update. Thanks for helping me

It's not on our prio list so no promises.

What would be interesting is what property you want to get

**Comment by Lulalaby** [comment]
> > Don't think we included a warning in code because it'd trigger on every message without any user involvement, it's been marked as deprecated in the docs though (or maybe we could make it a property?)
> 
> As I know  `MessageInteraction`  class will be removed from the codebase in the next update.

Most likely

**Comment by DIPx69** [comment]
> > I am using version 2.6 with the changes in the code, and my codebase is working fine. I hope these issue will be patched in the next update. Thanks for helping me
> 
> It's not on our prio list so no promises.
> 
> What would be interesting is what property you want to get

` name `

**Comment by Lulalaby** [comment]
> ` name `

This is a property of a deprecated and soon to be removed field **by discord**. Try finding another solution, we won't support specifically that, as outlined in my first response here
