### ISSUE TITLE
Extra attributes for slash commands

### ISSUE THREAD

**Issue by ii-Python** [Pycord-Development/pycord#426]
### Summary

The ability to add more attributes to slash commands (category, etc)

### What is the feature request for?

discord.ext.commands

### The Problem

In my bot, I have a help command based around slash commands.
Before using slash commands, I had each cog have a `.attr` dictionary for extra data on the cog, however I think it would be nice if this was implemented in slash commands as well. Simply having the ability to add extra data to a slash command so you can refer to it later would save a lot of time.

### The Ideal Solution

The new constructor (in my head):
```py
@commands.slash_command(guild_ids = [...], description = "A very nice slash command", category = "misc")
async def command(self, ctx):
    return ctx.respond("Hello!")
```

This could then be referred to via `bot.application_commands`.
An example on that:
```py
for command in self.bot.application_commands.items():
    print(command.name, command.category)
```

Ideally, the `SlashCommand` class would store any extra kwargs given to it.

### The Current Solution

I don't believe there is currently a way to do this in Pycord.

### Additional Context

I maintain my own fork of pycord, just for things like this.
My [implementation](https://github.com/ii-Python/discord/commit/b9d4bfc606bcd19f43e4e029aadc74a0ed1a336c) simply added `SlashCommand.category`, although it wouldn't be hard to add more.

**Comment by TheReaper62** [comment]
There was only `category` being added, is there anything else specifically you wanted to add?

**Comment by Rwarcards762** [comment]
Adding this in case anyone else finds this and gets stuck, since the "non-stale" version of this issue ended up not adding extra attributes... 

The ability to add extra attributes and reference them for Slash Command objects is incredibly useful for defining extra information, e.g. "category" or whatever else, in the declaration of the function rather than possibly adding work elsewhere to store extraneous information about functions.

A possible solution is to utilize the `__dict__` for a Slash Command object, like so:

```py
# Add extra attribute(s) in decorator
@bot.slash_command(name="TestCommand", description="A test command", category="Category1")

# access those attributes via the kwargs, since the Slash Command decorator takes in all kwargs
commandObject = bot.get_application_command('TestCommand')
commandObject.__dict__['__original_kwargs__']['category']
> Category1
```

It's a little bulky, but it works.
