### ISSUE TITLE
Bot does not run

### ISSUE THREAD

**Issue by ruan2007** [Pycord-Development/pycord#564]
### Summary

So.. my bot does not run, does not run the on_ready() function and all commands. nothing is displayed in the terminal

### Reproduction Steps

I dont think that is a bug in my code because i tried to run with another bot token and it runs perfectly
but when i try to run with my main bot (it has 62 guilds and around 40 thousand users) it does not work, its not giving any error on the terminal.

### Minimal Reproducible Code

My main file:
```Python
import os
import discord
from discord.ext import commands
from decouple import config


bot = commands.Bot(
	chunk_guilds_at_startup=False,
	help_command=None,
	activity=None,
	intents=discord.Intents.all()
)

async def set_presence():
	await bot.wait_until_ready()
	await bot.change_presence(activity=discord.Game(f'in {len(bot.guilds)} servers with {len(bot.users)} users!'))

for root, dirs, files in os.walk("./cogs"):
	for file in files:
		if file.endswith(".py"):
			nome = file[:-3]
			bot.load_extension(f"{root}.{nome}".replace("\\", ".").replace("./", "").replace("/", "."))

bot.loop.create_task(set_presence())
bot.run(config("TOKEN"))

```
### Expected Results

The bot starts normally and run the on_ready() function

### Actual Results

Nothing is displayed on the terminal, but i set it the logging to INFO and got several warnings like this:
2021-12-13 15:41:12,208:WARNING:discord.gateway: Shard ID None heartbeat blocked for more than 50 seconds..

### Intents

discord.Intents.all()

### System Information

- Python v3.10.0-final
- py-cord v2.0.0-alpha
    - py-cord pkg_resources: v2.0.0a4511+g16370371
- aiohttp v3.7.4.post0
- system info: Windows 10 10.0.19043

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by krittick** [comment]
Please provide an example of your code that is encountering the issue.

**Comment by ruan2007** [comment]
> Please provide an example of your code that is encountering the issue.

done

**Comment by krittick** [comment]
Does the issue occur if you don't use the `decouple` library and pass the token directly instead?

**Comment by ruan2007** [comment]
> Does the issue occur if you don't use the `decouple` library and pass the token directly instead?

Yes, this error occurs anyway with my main bot token.

**Comment by krittick** [comment]
More specifically, does it work if you do `bot.run("token")` instead of `bot.run(config("token"))`?

Also, have you tried regenerating the problematic token?

**Comment by ruan2007** [comment]
> More specifically, does it work if you do `bot.run("token")` instead of `bot.run(config("token"))`?
> 
> Also, have you tried regenerating the problematic token?

Does not work with `bot.run("token")`
I already tried regenerating the token, the issue still continues, its a strange issue that I've never seen it before in my project.

**Comment by krittick** [comment]
Are you still prefixing your token with "Bot" like you mentioned in Discord? If so, don't do that. Whoever told you that is wrong.

**Comment by ruan2007** [comment]
> Are you still prefixing your token with "Bot" like you mentioned in Discord? If so, don't do that. Whoever told you that is wrong.
No I'm not, i removed it.

**Comment by nerdguyahmad** [comment]
This isn't a library issue. The reason you're getting warnings when enabling logging is because you are doing something (probably in cogs) that is taking way too long and is blocking (not async). Common examples are web requests, image manipulation, querying database with a blocking library like pymongo instead of motor for MongoDB.

Since you said that your main bot that has relatively high traffic is causing problems, It's can be because you might be querying your database for each guild or each user with a blocking library and as you said that your ready event is dispatching properly it shows that you are doing the blocking task inside `on_ready` or after `on_ready`. 

If you're doing something with you're database, Consider using following libraries for respective database:

- MongoDB: motor (instead of pymongo)
- PostgreSQL: asyncpg
- SQLite: aiosqlite (instead of sqlite3) 

If none of this is the case, You should look through your code and figure out what is blocking your code and find a non-blocking workaround for it.
