### ISSUE TITLE
SlashCommand Groups Issues

### ISSUE THREAD

**Issue by Lulalaby** [Pycord-Development/pycord#574]
This issue is to keep track of the issues since we reworked groups.

**Comment by TheReaper62** [comment]
Bot `(discord.Bot)` is mising the `command_group` function
The image below shows the working version compared to the current version and it is clear that `command_group` was removed.
<img width="1280" alt="Screenshot 2021-12-16 at 12 59 41 PM" src="https://user-images.githubusercontent.com/34223146/146311243-98812438-d956-4709-a1f7-3557665046d9.png">

**Comment by VincentRPS** [comment]
> Bot `(discord.Bot)` is mising the `command_group` function
> The image below shows the working version compared to the current version and it is clear that `command_group` was removed.
> <img alt="Screenshot 2021-12-16 at 12 59 41 PM" width="1280" src="https://user-images.githubusercontent.com/34223146/146311243-98812438-d956-4709-a1f7-3557665046d9.png">

Dos not look like it was removed try create_group

**Comment by TigerNinja22** [comment]
This issue is coming for me:
`Ignoring exception in command autorole set:
Traceback (most recent call last):
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/discord/ext/commands/bot.py", line 882, in invoke
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/discord/ext/commands/core.py", line 1470, in invoke
    def owner_or_permissions(**perms):
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/discord/ext/commands/core.py", line 902, in invoke
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/discord/ext/commands/core.py", line 832, in prepare
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/discord/ext/commands/core.py", line 738, in _parse_arguments
    if hook is not None:
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/discord/ext/commands/core.py", line 572, in transform
    return param.default
discord.ext.commands.errors.MissingRequiredArgument: ctx is a required argument that is missing.`

It's not a slash command, just a normal command but it still occurs, in a command_group.
Kindly fix it.

**Comment by TheReaper62** [comment]
If its a new feature I think we should update examples

**Comment by krittick** [comment]
> This issue is coming for me:
> `Ignoring exception in command autorole set:
> Traceback (most recent call last):
>   File "/opt/virtualenvs/python3/lib/python3.8/site-packages/discord/ext/commands/bot.py", line 882, in invoke
>   File "/opt/virtualenvs/python3/lib/python3.8/site-packages/discord/ext/commands/core.py", line 1470, in invoke
>     def owner_or_permissions(**perms):
>   File "/opt/virtualenvs/python3/lib/python3.8/site-packages/discord/ext/commands/core.py", line 902, in invoke
>   File "/opt/virtualenvs/python3/lib/python3.8/site-packages/discord/ext/commands/core.py", line 832, in prepare
>   File "/opt/virtualenvs/python3/lib/python3.8/site-packages/discord/ext/commands/core.py", line 738, in _parse_arguments
>     if hook is not None:
>   File "/opt/virtualenvs/python3/lib/python3.8/site-packages/discord/ext/commands/core.py", line 572, in transform
>     return param.default
> discord.ext.commands.errors.MissingRequiredArgument: ctx is a required argument that is missing.`
> 
> It's not a slash command, just a normal command but it still occurs, in a command_group.
> Kindly fix it.

Please make sure you're using the latest update in the repo. This was (hopefully) fixed in #572 today.

**Comment by Dorukyum** [comment]
> Bot `(discord.Bot)` is mising the `command_group` function
> 
> The image below shows the working version compared to the current version and it is clear that `command_group` was removed.
> 
> <img width="1280" alt="Screenshot 2021-12-16 at 12 59 41 PM" src="https://user-images.githubusercontent.com/34223146/146311243-98812438-d956-4709-a1f7-3557665046d9.png">
> 
> 

It was renamed to create_group to prevent confusion with the name of the decorator method.

**Comment by timmypidashev** [comment]
And here i was about to submit an issue that the examples are broken...
