### ISSUE TITLE
Paginator does not work inside a class that inherits commands.DefaultHelpCommand

### ISSUE THREAD

**Issue by Mikask1** [Pycord-Development/pycord#651]
### Summary

The buttons fail to change the page on the paginator

### Reproduction Steps

1. Make a class that inherits `commands.DefaultHelpCommand`
2. Overwrite the `async def send_bot_help(self, mapping)` function
3. Make an instance of the `pages.Paginator` class named `paginator`
4. Write `await paginator.send(self.get_destination())`

### Minimal Reproducible Code

```python
class CustomHelpCommand(commands.DefaultHelpCommand):
    def __init__(self, **options):
        super().__init__(**options)

    async def send_bot_help(self, mapping):
        page_list = [discord.Embed(title="Page 1"), discord.Embed(title="Page 2")]
        
        paginator = pages.Paginator(
            pages=page_list)
        
        await paginator.send(self.get_destination())

bot = commands.Bot(command_prefix = "?", help_command=CustomHelpCommand())

@bot.event
async def on_ready():
    print(f"Logged in as {bot.user} (ID: {bot.user.id})")

bot.run(TOKEN)
```

### Expected Results

I am able to change the page by clicking the buttons

### Actual Results

The paginator showed `This interaction failed`

### Intents

None, ~~I don't even know how to use this~~

### System Information

- Python v3.9.5-final
- py-cord v2.0.0-alpha
    - py-cord pkg_resources: v2.0.0a4644+gf5c3e600
- aiohttp v3.7.4.post0
- system info: Windows 10 10.0.19043

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

I also want to implement the CustomHelpCommand class with a Dropdown (`discord.ui.Select`) so if possible I want that to also work. Here's the class that I made for that if it's helpful.

```
import discord
from discord.ext.pages import Paginator

class _Dropdown(discord.ui.Select):
    def __init__(self, 
                placeholder: str,
                options: list, 
                paginator: Paginator):
                
        self.paginator = paginator
        
        self.label_index = dict()
        for n, option in enumerate(options):
            self.label_index[option.label] = n

        super().__init__(
            placeholder=placeholder,
            min_values=1,
            max_values=1,
            options=options,
        )

    async def callback(self, interaction: discord.Interaction):
        page_number = self.label_index[self.values[0]]
        self.paginator.current_page = page_number
        await self.paginator.goto_page(interaction, page_number=page_number)

class _DropdownView(discord.ui.View):
    def __init__(self, 
                placeholder: str, 
                options: list, 
                paginator: Paginator):

        super().__init__()

        dropdown = _Dropdown(placeholder=placeholder, paginator=paginator, options=options)

        super().add_item(dropdown)

class DropdownPaginator(Paginator):
    def __init__(
                self: Paginator, 
                pages: list, 
                placeholder: str, 
                options: list, 
                show_indicator= True, 
                show_disabled= True):

        self.pages = pages

        view = _DropdownView(paginator=self, placeholder=placeholder, options=options)

        super().__init__(pages=self.pages, custom_view=view, show_indicator=show_indicator, show_disabled=show_disabled)
```

**Comment by Makiyu-py** [comment]
I somehow fixed this by replacing the argument on your Minimal Reproducible Code for `paginator.send` from `self.get_destination()` to `self.context`.

But still, this is a bug from both ends since `self.get_destination` function returns the destination channel, while `self.context` returns the current context which in turn did not register `self.user`. (see line)

https://github.com/Pycord-Development/pycord/blob/51dd856e9e07b16440790812a64eac0bf451633f/discord/ext/pages/pagination.py#L316-L317

Since `self.user` is `None`, the `interaction_check` would always return `False`.

https://github.com/Pycord-Development/pycord/blob/51dd856e9e07b16440790812a64eac0bf451633f/discord/ext/pages/pagination.py#L206-L209

And since the argument for the send function only requires the `messageable` keyword argument to be a `Messageable`, the send function allowed `self.get_destination()` since the `TextChannel` class inherit from `Messageable`.

**Comment by Mikask1** [comment]
That makes a lot of sense! Thanks a lot for fixing the bug on my end aswell.
