### ISSUE TITLE
Setting embed.description to None instead sets it to "None"

### ISSUE THREAD

**Issue by KosmicAnomaly** [Pycord-Development/pycord#744]
### Summary

Setting embed.description to None instead sets it to "None"

### Reproduction Steps

embed.description = None

### Minimal Reproducible Code

```python
embed = discord.Embed()
embed.description = None
```

### Expected Results

Remove the embed description

### Actual Results

Change the embed description to "None"

### Intents

discord.Intents.all()

### System Information

- Python v3.9.7-final
- py-cord v2.0.0-alpha
    - py-cord pkg_resources: v2.0.0a4757+g02e346db
- aiohttp v3.7.4.post0
- system info: Windows 10 10.0.22000

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by krittick** [comment]
This was done intentionally prior to pycord's existence here: https://github.com/Rapptz/discord.py/issues/6574

I do feel that it merits a discussion on whether this _should_ occur when explicitly setting an Embed parameter to `None` vs expecting users to provide `discord.Embed.Empty` to get that expected behavior instead, so I'm going to log a PR with a proposed fix.
