### ISSUE TITLE
Interaction Fail Event

### ISSUE THREAD

**Issue by Rxann** [Pycord-Development/pycord#89]
### Summary

Add an event for when a discord Interaction fails!

### What is the feature request for?

discord.ext.commands

### The Problem

I am trying to solve the issue of when you use a discord component, there is a chance the interaction fails. I would like there to be an interaction failed event. This would help with giving information to the user that is triggering the interaction.

### The Ideal Solution

Add an interaction fail event

### The Current Solution

None

**Comment by Rxann** [comment]
If discord doesn't dispatch this event, sorry for opening this

**Comment by Middledot** [comment]
Could you elaborate on the issue?

**Comment by Rxann** [comment]
Yes,

Sometimes when you use a discord component, you get an error in red text that says "interaction failed". I would like if there could be an event for when this occurs!

**Comment by MhmCats** [comment]
The "Interaction failed" thing happens when a user interacts with a message component and you don't respond to the interaction within three seconds. If this is because of an error in your code for a button/select callback and you are using the `discord.ui.View` API then the `on_error` method of `discord.ui.View` will get called and it will get passed the error, the item that was interacted with and the interaction object.

**Comment by CodeWithSwastik** [comment]
I'm assuming [this answer](https://github.com/Pycord-Development/pycord/issues/89#issuecomment-913631606) is satisfactory. I'll close this.
